# Generated by Django 3.2.9 on 2021-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_punlished', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Old')])),
            ],
        ),
    ]
